import type {
  AdminDestination,
  AdminAttraction,
  AdminHotel,
  AdminRestaurant,
  CuisineItem,
  DishItem,
  AdminExperience,
  MediaItem,
  VerificationRequest,
  DuplicatePair,
  WeeklySchedule,
} from '../types/admin'

const STORAGE_KEY = 'yatra_admin_operational_db_v1'

export interface OperationalDatabase {
  destinations: AdminDestination[]
  attractions: AdminAttraction[]
  hotels: AdminHotel[]
  restaurants: AdminRestaurant[]
  cuisines: CuisineItem[]
  dishes: DishItem[]
  experiences: AdminExperience[]
  media: MediaItem[]
  verifications: VerificationRequest[]
  duplicatePairs: DuplicatePair[]
}

const defaultWeeklySchedule = (open = '09:00', close = '18:00'): WeeklySchedule => {
  const day = {
    isOpen: true,
    windows: [{ open, close }],
  }
  return {
    monday: { ...day },
    tuesday: { ...day },
    wednesday: { ...day },
    thursday: { ...day },
    friday: { ...day },
    saturday: { ...day },
    sunday: { ...day },
  }
}

function getInitialDatabase(): OperationalDatabase {
  const destinations: AdminDestination[] = [
    {
      id: 'dest-udaipur',
      name: 'Udaipur',
      slug: 'udaipur',
      state: 'Rajasthan',
      region: 'Mewar',
      country: 'India',
      locality: 'Girwa',
      tagline: 'The City of Lakes & Royal Mewar Heritage',
      description: 'Set around a series of artificial lakes and known for its lavish royal residences, Udaipur is the historic capital of the kingdom of Mewar.',
      heroImage: '/images/places/city-palace.jpg',
      gallery: [
        '/images/places/city-palace.jpg',
        '/images/places/lake-pichola.jpg',
        '/images/places/jagdish-temple.jpg',
        '/images/places/bagore-ki-haveli.jpg',
      ],
      coordinates: { lat: 24.5854, lng: 73.7125 },
      bestSeason: 'October – March',
      bestDuration: '3–5 Days',
      approxBudgetPerDay: { budget: 1800, comfort: 4200, luxury: 12000 },
      tags: ['Heritage', 'Lakes', 'Palaces', 'Culture', 'Romantic'],
      travelStyles: ['Heritage & Architecture', 'Cultural & Spiritual', 'Romantic & Leisure'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 96,
      dataHealth: 94,
      lastVerified: '2026-09-08T09:00:00Z',
      verifiedBy: 'Saurabh Admin',
      attractionsCount: 8,
      hotelsCount: 6,
      restaurantsCount: 8,
      experiencesCount: 5,
    },
    {
      id: 'dest-jaipur',
      name: 'Jaipur',
      slug: 'jaipur',
      state: 'Rajasthan',
      region: 'Dhundhar',
      country: 'India',
      locality: 'Pink City',
      tagline: 'The Pink City of Fortresses & Royal Observatories',
      description: 'Capital of Rajasthan, famed for majestic hill forts, UNESCO World Heritage astronomical observatories, and vibrant bazaars.',
      heroImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1603288940316-4e43bf17730a?auto=format&fit=crop&w=800&q=80',
      ],
      coordinates: { lat: 26.9124, lng: 75.7873 },
      bestSeason: 'October – March',
      bestDuration: '3–4 Days',
      approxBudgetPerDay: { budget: 1600, comfort: 3800, luxury: 11000 },
      tags: ['Heritage', 'Forts', 'UNESCO', 'Shopping', 'Palaces'],
      travelStyles: ['Heritage & Architecture', 'Culinary Explorer'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 94,
      dataHealth: 92,
      lastVerified: '2026-09-07T14:30:00Z',
      verifiedBy: 'Saurabh Admin',
      attractionsCount: 7,
      hotelsCount: 5,
      restaurantsCount: 6,
      experiencesCount: 4,
    },
    {
      id: 'dest-agra',
      name: 'Agra',
      slug: 'agra',
      state: 'Uttar Pradesh',
      region: 'Braj',
      country: 'India',
      locality: 'Tajganj',
      tagline: 'Seat of the Mughal Empire & Eternal Marble Wonder',
      description: 'Home to the iconic Taj Mahal, Agra Fort, and Fatehpur Sikri—monumental wonders of Indo-Islamic Mughal architectural grandeur.',
      heroImage: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?auto=format&fit=crop&w=800&q=80',
      ],
      coordinates: { lat: 27.1767, lng: 78.0081 },
      bestSeason: 'October – March',
      bestDuration: '2–3 Days',
      approxBudgetPerDay: { budget: 1400, comfort: 3200, luxury: 9500 },
      tags: ['UNESCO', 'Mughal', 'Monuments', 'History'],
      travelStyles: ['Heritage & Architecture', 'Photography Expedition'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 92,
      dataHealth: 90,
      lastVerified: '2026-09-06T10:00:00Z',
      verifiedBy: 'Vikram Singh',
      attractionsCount: 6,
      hotelsCount: 4,
      restaurantsCount: 5,
      experiencesCount: 3,
    },
    {
      id: 'dest-varanasi',
      name: 'Varanasi',
      slug: 'varanasi',
      state: 'Uttar Pradesh',
      region: 'Purvanchal',
      country: 'India',
      locality: 'Kashi',
      tagline: 'The Eternal Spiritual Capital of India along the Holy Ganga',
      description: 'One of the oldest continuously inhabited cities in human history, known for sacred bathing ghats, evening Ganga Aarti, and silk weaving.',
      heroImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
      gallery: ['https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80'],
      coordinates: { lat: 25.3176, lng: 82.9739 },
      bestSeason: 'November – February',
      bestDuration: '2–3 Days',
      approxBudgetPerDay: { budget: 1200, comfort: 2800, luxury: 8000 },
      tags: ['Spiritual', 'Ghats', 'Ancient', 'Silk', 'Aarti'],
      travelStyles: ['Cultural & Spiritual', 'Culinary Explorer'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 90,
      dataHealth: 88,
      lastVerified: '2026-09-05T12:00:00Z',
      verifiedBy: 'Saurabh Admin',
      attractionsCount: 6,
      hotelsCount: 4,
      restaurantsCount: 5,
      experiencesCount: 3,
    },
    {
      id: 'dest-goa',
      name: 'Goa',
      slug: 'goa',
      state: 'Goa',
      region: 'Konkan',
      country: 'India',
      locality: 'Panaji',
      tagline: 'Sun-Kissed Beaches, Portuguese Latin Quarters & Coastal Flavours',
      description: 'A serene blend of Indian and Portuguese cultures, featuring UNESCO baroque churches, tropical spice plantations, and golden sandy shores.',
      heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
      gallery: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80'],
      coordinates: { lat: 15.2993, lng: 74.124 },
      bestSeason: 'November – February',
      bestDuration: '4–6 Days',
      approxBudgetPerDay: { budget: 2000, comfort: 4500, luxury: 14000 },
      tags: ['Beaches', 'Portuguese', 'Seafood', 'Nature', 'Leisure'],
      travelStyles: ['Relaxation & Wellness', 'Culinary Explorer'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 88,
      dataHealth: 86,
      lastVerified: '2026-09-04T16:00:00Z',
      verifiedBy: 'Saurabh Admin',
      attractionsCount: 7,
      hotelsCount: 6,
      restaurantsCount: 6,
      experiencesCount: 4,
    },
    {
      id: 'dest-hampi',
      name: 'Hampi',
      slug: 'hampi',
      state: 'Karnataka',
      region: 'Kishkindha',
      country: 'India',
      locality: 'Vijayanagara',
      tagline: 'Monumental Ruins of the Magnificent Vijayanagara Empire',
      description: 'A UNESCO World Heritage marvel of stone chariots, musical pillars, and monolithic boulders along the Tungabhadra River.',
      heroImage: 'https://images.unsplash.com/photo-1600100397608-f010e42e564d?auto=format&fit=crop&w=1200&q=80',
      gallery: ['https://images.unsplash.com/photo-1600100397608-f010e42e564d?auto=format&fit=crop&w=800&q=80'],
      coordinates: { lat: 15.335, lng: 76.46 },
      bestSeason: 'October – February',
      bestDuration: '2–3 Days',
      approxBudgetPerDay: { budget: 1400, comfort: 3200, luxury: 8500 },
      tags: ['UNESCO', 'Ruins', 'Architecture', 'Boulder', 'Ancient'],
      travelStyles: ['Heritage & Architecture', 'Photography Expedition'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 91,
      dataHealth: 90,
      lastVerified: '2026-09-03T11:00:00Z',
      verifiedBy: 'Saurabh Admin',
      attractionsCount: 6,
      hotelsCount: 3,
      restaurantsCount: 4,
      experiencesCount: 3,
    },
  ]

  const attractions: AdminAttraction[] = [
    {
      id: 'udaipur-city-palace',
      name: 'City Palace Complex',
      hindiName: 'सिटी पैलेस',
      category: 'palace',
      categoryLabel: 'Royal Palace Complex',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      description: 'A magnificent 400-year-old architectural marvel built atop a hill overlooking Lake Pichola, showcasing an eclectic fusion of Rajasthani and Mughal architectural styles with mirrored chambers, courtyards, and museum galleries.',
      shortDescription: 'Largest palace complex in Rajasthan overlooking Lake Pichola.',
      coordinates: { lat: 24.5764, lng: 73.6835 },
      address: 'Old City, Udaipur, Rajasthan 313001',
      heroImage: '/images/places/city-palace.jpg',
      images: [
        '/images/places/city-palace.jpg',
        '/images/places/lake-pichola.jpg',
      ],
      entryFee: {
        indian: 300,
        foreign: 300,
        student: 100,
        camera: 200,
        priceType: 'tiered',
      },
      openingHours: defaultWeeklySchedule('09:00', '21:00'),
      closedDays: [],
      bestTime: {
        bestTimeOfDay: 'Morning',
        bestTimeDescription: 'Arrive at 9:00 AM sharp to beat the crowd and enjoy pleasant natural sunlight through the stained glass windows.',
        bestSeason: 'October – March',
      },
      recommendedVisitDurationMin: 150,
      importanceScore: 10,
      culturalScore: 9.8,
      historicalScore: 9.9,
      popularityScore: 9.9,
      uniquenessScore: 9.7,
      priorityCategory: 'must_see',
      familyFriendly: true,
      accessibility: true,
      photography: true,
      tags: ['Palace', 'Mewar', 'Museum', 'Lake View', 'Architecture'],
      status: 'published',
      verificationStatus: 'verified',
      source: 'Mewar Royal Trust & Physical ASI Field Verification',
      lastVerified: '2026-09-08T09:00:00Z',
      verifiedBy: 'Saurabh Admin',
      usedInTripsCount: 1420,
      usedInCollectionsCount: 8,
    },
    {
      id: 'udaipur-lake-pichola',
      name: 'Lake Pichola & Boat Ghat',
      hindiName: 'पिछोला झील',
      category: 'lake',
      categoryLabel: 'Freshwater Lake & Boat Cruise',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      description: 'An iconic artificial freshwater lake created in the 14th century, surrounded by majestic palaces, bathing ghats, and hill temples. Boat rides offer breathtaking views of Taj Lake Palace and Jag Mandir.',
      shortDescription: 'Famous romantic lake with boat rides to Jag Mandir.',
      coordinates: { lat: 24.5753, lng: 73.6783 },
      address: 'Rameshwar Ghat, City Palace Jetty, Udaipur',
      heroImage: '/images/places/lake-pichola.jpg',
      images: [
        '/images/places/lake-pichola.jpg',
        '/images/places/city-palace.jpg',
      ],
      entryFee: {
        indian: 450,
        foreign: 800,
        priceType: 'fixed',
      },
      openingHours: defaultWeeklySchedule('09:30', '18:30'),
      closedDays: [],
      bestTime: {
        bestTimeOfDay: 'Sunset',
        bestTimeDescription: 'Sunset boat rides (5:00 PM – 6:15 PM) provide golden reflections against the marble walls of Lake Palace.',
        bestSeason: 'October – March',
      },
      recommendedVisitDurationMin: 90,
      importanceScore: 9.8,
      culturalScore: 9.2,
      historicalScore: 8.8,
      popularityScore: 9.8,
      uniquenessScore: 9.5,
      priorityCategory: 'must_see',
      familyFriendly: true,
      accessibility: false,
      photography: true,
      tags: ['Lake', 'Sunset', 'Boat Cruise', 'Jag Mandir', 'Romantic'],
      status: 'published',
      verificationStatus: 'verified',
      source: 'Udaipur Tourism Department & Field Audit',
      lastVerified: '2026-09-08T08:30:00Z',
      verifiedBy: 'Saurabh Admin',
      usedInTripsCount: 1350,
      usedInCollectionsCount: 7,
    },
    {
      id: 'udaipur-jagdish-temple',
      name: 'Jagdish Temple',
      hindiName: 'जगदीश मंदिर',
      category: 'temple',
      categoryLabel: '1651 AD Indo-Aryan Stone Temple',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      description: 'Consecrated in 1651 AD by Maharana Jagat Singh, this three-storied Indo-Aryan stone temple is dedicated to Lord Vishnu and features intricately carved pillars, painted ceilings, and sculpted elephants.',
      shortDescription: 'Majestic 17th-century carved stone temple right by City Palace gate.',
      coordinates: { lat: 24.5794, lng: 73.6841 },
      address: 'Bada Bazaar, Old City, Udaipur 313001',
      heroImage: '/images/places/jagdish-temple.jpg',
      images: [
        '/images/places/jagdish-temple.jpg',
      ],
      entryFee: {
        indian: 0,
        foreign: 0,
        priceType: 'free',
      },
      openingHours: {
        monday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
        tuesday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
        wednesday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
        thursday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
        friday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
        saturday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
        sunday: { isOpen: true, windows: [{ open: '05:00', close: '12:30' }, { open: '16:00', close: '21:00' }] },
      },
      closedDays: [],
      bestTime: {
        bestTimeOfDay: 'Early Morning',
        bestTimeDescription: 'Attend the 5:30 AM early morning aarti to experience devotional chants and morning lamps in undisturbed peace.',
        bestSeason: 'Year-round',
      },
      recommendedVisitDurationMin: 45,
      importanceScore: 8.9,
      culturalScore: 9.6,
      historicalScore: 9.4,
      popularityScore: 8.7,
      uniquenessScore: 9.1,
      priorityCategory: 'recommended',
      familyFriendly: true,
      accessibility: false,
      photography: false,
      tags: ['Temple', 'Indo-Aryan', 'Spiritual', 'Architecture', 'Free'],
      status: 'published',
      verificationStatus: 'verified',
      source: 'ASI Monument Registry & On-site Verification',
      lastVerified: '2026-09-08T07:15:00Z',
      verifiedBy: 'Saurabh Admin',
      usedInTripsCount: 980,
      usedInCollectionsCount: 5,
    },
    {
      id: 'udaipur-bagore-ki-haveli',
      name: 'Bagore Ki Haveli & Dharohar',
      hindiName: 'बागोर की हवेली',
      category: 'heritage',
      categoryLabel: '18th-century Waterfront Mansion & Folk Art',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      description: 'An authentic 18th-century haveli standing right at Gangaur Ghat with over a hundred rooms displaying royal costumes, glass inlay work, and the famed nightly Dharohar Rajasthani folk dance.',
      shortDescription: 'Lakeside mansion featuring nightly Rajasthani folk dance performances.',
      coordinates: { lat: 24.5801, lng: 73.6811 },
      address: 'Gangaur Ghat Marg, Old City, Udaipur 313001',
      heroImage: '/images/places/bagore-ki-haveli.jpg',
      images: ['/images/places/bagore-ki-haveli.jpg'],
      entryFee: {
        indian: 100,
        foreign: 150,
        camera: 100,
        priceType: 'tiered',
      },
      openingHours: {
        monday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }], specialNote: '7:00 PM is Dharohar Folk Dance' },
        tuesday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }] },
        wednesday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }] },
        thursday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }] },
        friday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }] },
        saturday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }] },
        sunday: { isOpen: true, windows: [{ open: '09:30', close: '17:30' }, { open: '19:00', close: '20:00' }] },
      },
      closedDays: [],
      bestTime: {
        bestTimeOfDay: 'Evening',
        bestTimeDescription: 'Arrive by 6:15 PM to reserve front-row floor mats for the 7:00 PM Dharohar folk dance and puppet show.',
        bestSeason: 'October – March',
      },
      recommendedVisitDurationMin: 75,
      importanceScore: 8.8,
      culturalScore: 9.7,
      historicalScore: 9.0,
      popularityScore: 9.3,
      uniquenessScore: 9.2,
      priorityCategory: 'must_see',
      familyFriendly: true,
      accessibility: false,
      photography: true,
      tags: ['Folk Dance', 'Haveli', 'Museum', 'Waterfront', 'Culture'],
      status: 'published',
      verificationStatus: 'verified',
      source: 'West Zone Cultural Centre (WZCC)',
      lastVerified: '2026-09-07T18:00:00Z',
      verifiedBy: 'Saurabh Admin',
      usedInTripsCount: 1120,
      usedInCollectionsCount: 6,
    },
    {
      id: 'udaipur-sajjangarh',
      name: 'Monsoon Palace (Sajjangarh)',
      hindiName: 'सज्जनगढ़ पैलेस',
      category: 'palace',
      categoryLabel: 'Hilltop Monsoon Palace & Sanctuary',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      description: 'Perched 3,100 feet above sea level on the peak of Bansdara Mountain, this 1884 palatial residence was constructed by Maharana Sajjan Singh to watch monsoon clouds gather across the Aravalli hills.',
      shortDescription: 'High-altitude palace offering panoramic sunset vistas over Udaipur.',
      coordinates: { lat: 24.5936, lng: 73.6394 },
      address: 'Sajjan Garh Road, Bansdara Peak, Udaipur 313001',
      heroImage: '/images/places/sajjangarh.jpg',
      images: ['/images/places/sajjangarh.jpg'],
      entryFee: {
        indian: 110,
        foreign: 300,
        camera: 100,
        priceType: 'tiered',
      },
      openingHours: defaultWeeklySchedule('09:00', '18:00'),
      closedDays: [],
      bestTime: {
        bestTimeOfDay: 'Sunset',
        bestTimeDescription: 'Leave the city by 4:15 PM to reach the mountain peak before 5:00 PM for the sunset over the Aravalli range.',
        bestSeason: 'July – February',
      },
      recommendedVisitDurationMin: 120,
      importanceScore: 8.6,
      culturalScore: 8.4,
      historicalScore: 8.9,
      popularityScore: 9.2,
      uniquenessScore: 9.4,
      priorityCategory: 'recommended',
      familyFriendly: true,
      accessibility: false,
      photography: true,
      tags: ['Sunset', 'Mountain View', 'Palace', 'Wildlife', 'Aravalli'],
      status: 'published',
      verificationStatus: 'verified',
      source: 'Rajasthan Forest Department & ASI Verification',
      lastVerified: '2026-09-06T17:00:00Z',
      verifiedBy: 'Saurabh Admin',
      usedInTripsCount: 890,
      usedInCollectionsCount: 4,
    },
    {
      id: 'udaipur-saheliyon-ki-bari',
      name: 'Saheliyon Ki Bari',
      hindiName: 'सहेलियों की बाड़ी',
      category: 'heritage',
      categoryLabel: 'Royal Fountains & Lotus Pools Garden',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      description: 'Designed by Maharana Sangram Singh II in the 18th century as a secluded oasis for the royal maidens, featuring marble elephant fountains, rain fountains fed by Fateh Sagar Lake, and lotus pools.',
      shortDescription: 'Historic royal garden known for marble fountains and lotus ponds.',
      coordinates: { lat: 24.6028, lng: 73.6872 },
      address: 'Saheli Marg, New Fatehpura, Udaipur 313001',
      heroImage: '/images/places/saheliyon-ki-bari.jpg',
      images: ['/images/places/saheliyon-ki-bari.jpg'],
      entryFee: {
        indian: 20,
        foreign: 100,
        priceType: 'fixed',
      },
      openingHours: defaultWeeklySchedule('09:00', '19:00'),
      closedDays: [],
      bestTime: {
        bestTimeOfDay: 'Morning',
        bestTimeDescription: 'Visit between 9:30 AM and 11:30 AM when the gravity-fed fountains are fully turned on and morning dew lingers on the lotus leaves.',
        bestSeason: 'October – March',
      },
      recommendedVisitDurationMin: 60,
      importanceScore: 8.0,
      culturalScore: 8.6,
      historicalScore: 8.7,
      popularityScore: 8.4,
      uniquenessScore: 8.5,
      priorityCategory: 'optional',
      familyFriendly: true,
      accessibility: true,
      photography: true,
      tags: ['Garden', 'Fountains', 'Lotus Pond', 'Relaxing', 'Heritage'],
      status: 'published',
      verificationStatus: 'verified',
      source: 'Archeological Survey of Rajasthan',
      lastVerified: '2026-09-05T11:00:00Z',
      verifiedBy: 'Saurabh Admin',
      usedInTripsCount: 650,
      usedInCollectionsCount: 3,
    },
  ]

  const hotels: AdminHotel[] = [
    {
      id: 'hotel-udaivilas',
      name: 'The Oberoi Udaivilas',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      coordinates: { lat: 24.5772, lng: 73.6705 },
      address: 'Badi-Gorela-Mulla Talai Rd, Haridas Ji Ki Magri, Udaipur 313001',
      description: 'World-renowned luxury heritage palace resort spread across 50 acres on the banks of Lake Pichola, featuring domes, reflection pools, and private boat transfers.',
      heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
      images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80'],
      baseEstimatedPrice: 38000,
      livePrice: 42500,
      isLivePricing: true,
      rating: 4.9,
      reviewsCount: 1240,
      tier: 'luxury',
      type: 'Luxury Heritage Resort',
      amenities: ['Private Boat Arrival', 'Ayurvedic Spa', 'Lakefront Dining', 'Butler Service', 'Infinity Pools'],
      roomTypes: ['Premier Room with Pool View', 'Luxury Suite with Private Pool', 'Kohinoor Suite'],
      contactPhone: '+91 294 2433300',
      website: 'https://www.oberoihotels.com/hotels-in-udaipur-udaivilas/',
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-08T09:00:00Z',
      verifiedBy: 'Saurabh Admin',
    },
    {
      id: 'hotel-fateh-garh',
      name: 'Fateh Garh Heritage Resort',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      coordinates: { lat: 24.582, lng: 73.645 },
      address: 'Sisarma, Udaipur, Rajasthan 313001',
      description: 'Pioneering sanctuary built from recycled architectural heritage materials high on the Sisarma hill, offering jaw-dropping 360-degree vistas over Udaipur valley.',
      heroImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80',
      images: ['https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80'],
      baseEstimatedPrice: 9500,
      isLivePricing: false,
      rating: 4.6,
      reviewsCount: 680,
      tier: 'comfort',
      type: 'Boutique Heritage Palace',
      amenities: ['Hilltop Infinity Pool', 'Vintage Car Rides', 'Zip-line', 'Organic Dining'],
      roomTypes: ['Renaissance Room', 'Heritage Chamber', 'Plunge Pool Suite'],
      contactPhone: '+91 86969 45101',
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-07T12:00:00Z',
      verifiedBy: 'Saurabh Admin',
    },
    {
      id: 'hotel-madri-haveli',
      name: 'Madri Haveli Boutique Stay',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      coordinates: { lat: 24.5815, lng: 73.6828 },
      address: '70, Ganesh Ghati, Chandpole, Udaipur 313001',
      description: 'A 300-year-old meticulously restored haveli with arched stone pillars, rooftop dining, and warm traditional Mewari hospitality in the historic old quarters.',
      heroImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=80',
      images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80'],
      baseEstimatedPrice: 3200,
      isLivePricing: false,
      rating: 4.5,
      reviewsCount: 420,
      tier: 'budget',
      type: 'Historic Haveli',
      amenities: ['Rooftop Restaurant', 'Free Wi-Fi', 'Walking Tour Desk', 'Heritage Decor'],
      roomTypes: ['Standard Heritage', 'Deluxe Mewari Room'],
      contactPhone: '+91 294 2413377',
      featured: false,
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-06T15:00:00Z',
      verifiedBy: 'Pooja Verma',
    },
  ]

  const restaurants: AdminRestaurant[] = [
    {
      id: 'rest-ambrai',
      name: 'Ambrai Restaurant',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      coordinates: { lat: 24.5806, lng: 73.6792 },
      address: 'Amet Haveli, Ambavgarh, Udaipur 313001',
      cuisine: 'Mewari & North Indian',
      cuisineId: 'cuisine-rajasthani',
      priceRange: 'fine_dining',
      priceForTwo: 2800,
      rating: 4.8,
      openingHours: '12:30 PM – 3:30 PM, 6:30 PM – 10:30 PM',
      closedDays: [],
      isVeg: false,
      isVegan: false,
      isJainFriendly: true,
      localSpecialties: ['Laal Maas', 'Mewari Khad Khargosh', 'Dal Baati Churma'],
      mustTryDishes: ['Junglee Maas', 'Ker Sangri', 'Garlic Naan'],
      description: 'Waterfront dining at Amet Haveli directly facing City Palace and Lake Palace illuminated at night.',
      heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80',
      images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-08T09:00:00Z',
      verifiedBy: 'Saurabh Admin',
    },
    {
      id: 'rest-natraj',
      name: 'Natraj Dining Hall & Restaurant',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      coordinates: { lat: 24.5888, lng: 73.6982 },
      address: 'Near Railway Station, Udaipur 313001',
      cuisine: 'Traditional Rajasthani & Gujarati Thali',
      cuisineId: 'cuisine-rajasthani',
      priceRange: 'budget',
      priceForTwo: 600,
      rating: 4.7,
      openingHours: '11:00 AM – 3:30 PM, 6:30 PM – 10:30 PM',
      closedDays: [],
      isVeg: true,
      isVegan: false,
      isJainFriendly: true,
      localSpecialties: ['Unlimited Royal Mewari Thali', 'Gatte Ki Sabzi', 'Dal Baati Churma'],
      mustTryDishes: ['Rajasthani Kadhi', 'Malpua', 'Churma Ladoo'],
      description: 'Legendary, bustling vegetarian dining hall beloved by locals for hearty authentic unlimited thalis.',
      heroImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=80',
      images: ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-07T14:00:00Z',
      verifiedBy: 'Saurabh Admin',
    },
    {
      id: 'rest-jagdish-kachori',
      name: 'Jagdish Mishthan Bhandar',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      coordinates: { lat: 24.582, lng: 73.6855 },
      address: 'Near Jagdish Temple, Old City, Udaipur',
      cuisine: 'Mewari Street Snacks & Sweets',
      cuisineId: 'cuisine-rajasthani',
      priceRange: 'budget',
      priceForTwo: 180,
      rating: 4.6,
      openingHours: '07:00 AM – 09:30 PM',
      closedDays: [],
      isVeg: true,
      isVegan: false,
      isJainFriendly: true,
      localSpecialties: ['Pyaaz Kachori', 'Hing Mirchi Vada', 'Ghewar'],
      mustTryDishes: ['Crispy Pyaaz Kachori with Mint Chutney', 'Jalebi'],
      description: 'Historic breakfast street counter serving steaming hot kachoris and fresh jalebi since 1952.',
      heroImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=80',
      images: ['https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80'],
      featured: false,
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-06T11:00:00Z',
      verifiedBy: 'Pooja Verma',
    },
  ]

  const cuisines: CuisineItem[] = [
    {
      id: 'cuisine-rajasthani',
      name: 'Rajasthani & Mewari',
      region: 'Northwest India / Rajasthan',
      description: 'Flavours shaped by desert arid conditions and warrior royalty, renowned for slow-cooked gravies, ghee-rich bread, and sun-dried spices.',
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
      destinationIds: ['dest-udaipur', 'dest-jaipur'],
      dishCount: 14,
      signatureDishes: ['Dal Baati Churma', 'Laal Maas', 'Gatte Ki Sabzi', 'Ker Sangri', 'Pyaaz Kachori'],
    },
    {
      id: 'cuisine-awadhi',
      name: 'Awadhi & Mughlai',
      region: 'Uttar Pradesh',
      description: 'Dum-cooked royal culinary traditions of the Nawabs of Lucknow and Mughal emperors, featuring aromatic saffron, cardamom, and succulent kebabs.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
      destinationIds: ['dest-agra', 'dest-varanasi'],
      dishCount: 16,
      signatureDishes: ['Petha', 'Galouti Kebab', 'Bedmi Poori', 'Tunday Kebab'],
    },
    {
      id: 'cuisine-goan',
      name: 'Goan Coastal & Saraswat',
      region: 'Konkan / West Coast',
      description: 'Unique confluence of Hindu Saraswat coastal spices and Portuguese Catholic vinegar-infused marinades.',
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      destinationIds: ['dest-goa'],
      dishCount: 12,
      signatureDishes: ['Goan Fish Curry', 'Chicken Xacuti', 'Bebinca', 'Prawn Balchão'],
    },
  ]

  const dishes: DishItem[] = [
    {
      id: 'dish-dal-baati',
      name: 'Dal Baati Churma',
      cuisineId: 'cuisine-rajasthani',
      cuisineName: 'Rajasthani & Mewari',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      isVeg: true,
      priceEstimate: 320,
      description: 'Crispy hard wheat balls baked over cow-dung ember fires, dipped in pure desi ghee, paired with spicy mixed-lentil curry and sweet jaggery churma powder.',
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
      recommendedRestaurantIds: ['rest-natraj', 'rest-ambrai'],
      flavorProfile: 'Rich, Savoury, Earthy, Ghee-Infused',
    },
    {
      id: 'dish-laal-maas',
      name: 'Mewari Laal Maas',
      cuisineId: 'cuisine-rajasthani',
      cuisineName: 'Rajasthani & Mewari',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      isVeg: false,
      priceEstimate: 650,
      description: 'Fiery royal mutton preparation slow-cooked with Mathania red chillies, garlic, curd, and smoked with charcoal cloves.',
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      recommendedRestaurantIds: ['rest-ambrai'],
      flavorProfile: 'Spicy, Smoked, Piquant, Aromatic',
    },
    {
      id: 'dish-kachori',
      name: 'Crispy Pyaaz Kachori',
      cuisineId: 'cuisine-rajasthani',
      cuisineName: 'Rajasthani & Mewari',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      isVeg: true,
      priceEstimate: 35,
      description: 'Flaky pastry stuffed with spiced caramelized onions, fennel, and coriander seeds, served piping hot with tamarind chutney.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
      recommendedRestaurantIds: ['rest-jagdish-kachori'],
      flavorProfile: 'Crispy, Tangy, Spiced',
    },
  ]

  const experiences: AdminExperience[] = [
    {
      id: 'exp-gangaur-ghat-walk',
      title: 'Heritage Walk through Old City Bazaars & Gangaur Ghat',
      category: 'cultural',
      categoryLabel: 'Guided Heritage Walk',
      location: 'Old City, Udaipur',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      duration: '2.5 Hours',
      durationMin: 150,
      price: 1200,
      bestTime: '08:00 AM – 10:30 AM',
      season: 'October – March',
      coordinates: { lat: 24.58, lng: 73.682 },
      highlights: [
        'Explore 300-year-old painted haveli alleyways',
        'Meet traditional miniature painting artisans',
        'Sample freshly made kachori and spiced tea',
      ],
      description: 'An intimate morning walking journey guided by a local historian uncovering forgotten courtyards and haveli gates of Mewar.',
      heroImage: '/images/places/bagore-ki-haveli.jpg',
      images: ['/images/places/bagore-ki-haveli.jpg'],
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-08T08:00:00Z',
      verifiedBy: 'Saurabh Admin',
    },
    {
      id: 'exp-dharohar-folk-dance',
      title: 'Dharohar Evening Rajasthani Folk Dance & Puppet Performance',
      category: 'cultural',
      categoryLabel: 'Traditional Performing Arts',
      location: 'Bagore Ki Haveli, Gangaur Ghat',
      destinationId: 'dest-udaipur',
      destinationName: 'Udaipur',
      duration: '1 Hour',
      durationMin: 60,
      price: 150,
      bestTime: '07:00 PM – 08:00 PM',
      season: 'Year-round',
      coordinates: { lat: 24.5801, lng: 73.6811 },
      highlights: [
        'Bhavai brass pot balancing dance on glass shards',
        'Authentic Mewari puppet theatre',
        'Live sarangi and dholak musical accompaniment',
      ],
      description: 'World-acclaimed cultural performance showcasing living folklore of desert Rajasthan inside an illuminated historic neem courtyard.',
      heroImage: '/images/places/bagore-ki-haveli.jpg',
      images: ['/images/places/bagore-ki-haveli.jpg'],
      status: 'published',
      verificationStatus: 'verified',
      lastVerified: '2026-09-07T19:00:00Z',
      verifiedBy: 'Saurabh Admin',
    },
  ]

  const media: MediaItem[] = [
    {
      id: 'media-001',
      title: 'City Palace Complex Mewar Facade',
      url: '/images/places/city-palace.jpg',
      altText: '400-year-old Udaipur City Palace complex above Lake Pichola',
      caption: 'Main entrance gate of Udaipur City Palace during clear daylight',
      source: "Trippin' Bharat Authentic Field Archive",
      license: 'ASI Verified',
      attribution: "Trippin' Bharat Official Heritage Photography Team",
      uploadedBy: 'Saurabh Admin',
      createdAt: '2026-08-15T10:00:00Z',
      fileSize: '1.4 MB',
      dimensions: '2400 x 1600 px',
      format: 'JPEG',
      usedBy: [
        { entityType: 'destination', entityId: 'dest-udaipur', entityName: 'Udaipur' },
        { entityType: 'attraction', entityId: 'udaipur-city-palace', entityName: 'City Palace Complex' },
      ],
    },
    {
      id: 'media-002',
      title: 'Lake Pichola Water Sunset',
      url: '/images/places/lake-pichola.jpg',
      altText: 'Lake Pichola waters reflecting golden hour sunset with boat rides',
      caption: 'Sunset boat tour on Lake Pichola overlooking Taj Lake Palace',
      source: "Trippin' Bharat Authentic Field Archive",
      license: 'ASI Verified',
      attribution: "Trippin' Bharat Official Heritage Photography Team",
      uploadedBy: 'Saurabh Admin',
      createdAt: '2026-08-15T10:30:00Z',
      fileSize: '1.2 MB',
      dimensions: '2400 x 1500 px',
      format: 'JPEG',
      usedBy: [
        { entityType: 'destination', entityId: 'dest-udaipur', entityName: 'Udaipur' },
        { entityType: 'attraction', entityId: 'udaipur-lake-pichola', entityName: 'Lake Pichola & Boat Ghat' },
      ],
    },
    {
      id: 'media-003',
      title: 'Jagdish Temple Stone Carvings',
      url: '/images/places/jagdish-temple.jpg',
      altText: 'Intricate 1651 AD Indo-Aryan stone shikhara of Jagdish Temple Udaipur',
      caption: 'Carved shikhara and entrance steps of Jagdish Temple',
      source: "Trippin' Bharat Authentic Field Archive",
      license: 'ASI Verified',
      attribution: 'ASI Udaipur Circle Documentation',
      uploadedBy: 'Saurabh Admin',
      createdAt: '2026-08-15T11:00:00Z',
      fileSize: '1.8 MB',
      dimensions: '2400 x 1800 px',
      format: 'JPEG',
      usedBy: [
        { entityType: 'attraction', entityId: 'udaipur-jagdish-temple', entityName: 'Jagdish Temple' },
      ],
    },
  ]

  const verifications: VerificationRequest[] = [
    {
      id: 'verif-001',
      entityType: 'attraction',
      entityId: 'udaipur-sajjangarh',
      entityName: 'Monsoon Palace (Sajjangarh)',
      destinationName: 'Udaipur',
      submittedBy: 'Tourism Data Editor',
      submittedAt: '2026-09-08T07:45:00Z',
      currentStatus: 'pending_review',
      changesSummary: 'Updated entry ticket prices (Foreigners: ₹300) and evening jeep tariff to summit.',
      sourceProof: 'Official ticket counter circular published by Rajasthan Forest Dept.',
    },
    {
      id: 'verif-002',
      entityType: 'restaurant',
      entityId: 'rest-ambrai',
      entityName: 'Ambrai Restaurant',
      destinationName: 'Udaipur',
      submittedBy: 'Content Admin',
      submittedAt: '2026-09-08T06:15:00Z',
      currentStatus: 'pending_review',
      changesSummary: 'Verified newly added Jain-friendly dining options and reservation slot rules.',
      sourceProof: 'Direct confirmation with Amet Haveli management.',
    },
  ]

  const duplicatePairs: DuplicatePair[] = [
    {
      id: 'dup-001',
      similarityPercentage: 94,
      distanceMeters: 65,
      reason: 'Extremely high name similarity and shared geographic coordinates near Lake Pichola.',
      recordA: {
        id: 'udaipur-city-palace',
        name: 'City Palace Complex',
        destination: 'Udaipur',
        category: 'Palace',
        coordinates: { lat: 24.5764, lng: 73.6835 },
        description: 'A magnificent 400-year-old architectural marvel built atop a hill overlooking Lake Pichola.',
        images: ['/images/places/city-palace.jpg'],
        openingHours: '09:00 AM – 09:00 PM',
        entryFee: 300,
        lastVerified: '2026-09-08',
      },
      recordB: {
        id: 'udaipur-city-palace-dup',
        name: 'City Palace, Udaipur (Royal Museum)',
        destination: 'Udaipur',
        category: 'Museum',
        coordinates: { lat: 24.5765, lng: 73.6836 },
        description: 'Old palace museum containing Mewar weaponry, silver thrones, and royal crystal galleries.',
        images: ['/images/places/city-palace.jpg'],
        openingHours: '09:30 AM – 05:30 PM',
        entryFee: 300,
        lastVerified: '2026-08-10',
      },
      status: 'pending',
    },
    {
      id: 'dup-002',
      similarityPercentage: 88,
      distanceMeters: 140,
      reason: 'Similar tourist spot tagged under different category names at Gangaur Ghat.',
      recordA: {
        id: 'udaipur-bagore-ki-haveli',
        name: 'Bagore Ki Haveli & Dharohar',
        destination: 'Udaipur',
        category: 'Heritage',
        coordinates: { lat: 24.5801, lng: 73.6811 },
        description: 'An authentic 18th-century haveli standing right at Gangaur Ghat with over a hundred rooms.',
        images: ['/images/places/bagore-ki-haveli.jpg'],
        openingHours: '09:30 AM – 08:00 PM',
        entryFee: 100,
        lastVerified: '2026-09-07',
      },
      recordB: {
        id: 'udaipur-dharohar-dance-dup',
        name: 'Dharohar Folk Dance Show Udaipur',
        destination: 'Udaipur',
        category: 'Experience',
        coordinates: { lat: 24.5802, lng: 73.6812 },
        description: 'Traditional evening dance show with bhavai pot balancing.',
        images: ['/images/places/bagore-ki-haveli.jpg'],
        openingHours: '07:00 PM – 08:00 PM',
        entryFee: 150,
        lastVerified: '2026-07-20',
      },
      status: 'pending',
    },
  ]

  return {
    destinations,
    attractions,
    hotels,
    restaurants,
    cuisines,
    dishes,
    experiences,
    media,
    verifications,
    duplicatePairs,
  }
}

class AdminStorageService {
  private db: OperationalDatabase

  constructor() {
    this.db = this.loadDatabase()
  }

  private loadDatabase(): OperationalDatabase {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored) {
        return JSON.parse(stored)
      }
    } catch (e) {
      console.warn('Failed to load operational DB from localStorage:', e)
    }
    const initial = getInitialDatabase()
    this.saveDatabase(initial)
    return initial
  }

  private saveDatabase(data: OperationalDatabase) {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data))
      // Broadcast update event so the public portal or listeners immediately update
      if (typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('yatra_admin_data_changed', { detail: { timestamp: Date.now() } }))
      }
    } catch (e) {
      console.warn('LocalStorage save failed:', e)
    }
  }

  getDb(): OperationalDatabase {
    return this.db
  }

  saveDb(updater: (prev: OperationalDatabase) => OperationalDatabase) {
    this.db = updater(this.db)
    this.saveDatabase(this.db)
  }

  resetToDefaults() {
    this.db = getInitialDatabase()
    this.saveDatabase(this.db)
  }
}

export const adminStorage = new AdminStorageService()
