import { User } from '../models/User.js'
import { Destination } from '../models/Destination.js'
import { Attraction } from '../models/Attraction.js'
import { Hotel } from '../models/Hotel.js'
import { Restaurant } from '../models/Restaurant.js'
import { Cuisine } from '../models/Cuisine.js'
import { Dish } from '../models/Dish.js'
import { Experience } from '../models/Experience.js'
import { MediaItem } from '../models/MediaItem.js'
import { VerificationRequest } from '../models/VerificationRequest.js'
import { isDbConnected } from '../config/database.js'

export async function seedDatabase(force = false) {
  if (!isDbConnected()) {
    console.log('ℹ️ DB not connected, skipping DB seeder.')
    return
  }

  try {
    const destCount = await Destination.countDocuments()
    if (destCount > 0 && !force) {
      console.log(`✅ Database already seeded (${destCount} destinations found).`)
      return
    }

    console.log('🌱 Seeding initial authentic tourism data into MongoDB...')

    // 1. Seed Users (Admin & Traveler)
    await User.deleteMany({})
    const adminUser = await User.create({
      name: 'Operations Admin',
      email: 'admin@yatra.in',
      password: 'password123',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    })

    const travelerUser = await User.create({
      name: 'Aarav Sharma',
      email: 'traveler@yatra.in',
      password: 'password123',
      role: 'user',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    })

    console.log(`👤 Created Users: admin@yatra.in & traveler@yatra.in (password: password123)`)

    // 2. Clear collections
    await Destination.deleteMany({})
    await Attraction.deleteMany({})
    await Hotel.deleteMany({})
    await Restaurant.deleteMany({})
    await Cuisine.deleteMany({})
    await Dish.deleteMany({})
    await Experience.deleteMany({})
    await MediaItem.deleteMany({})
    await VerificationRequest.deleteMany({})

    // 3. Seed Udaipur Destination
    const udaipur = await Destination.create({
      name: 'Udaipur',
      slug: 'udaipur',
      state: 'Rajasthan',
      region: 'Mewar',
      country: 'India',
      locality: 'Girwa',
      tagline: 'City of Lakes · Mewar Heritage · Palaces & Living Art',
      description: 'Founded in 1559 by Maharana Udai Singh II as the historic capital of the Mewar Kingdom. Renowned globally for its iconic marble palaces reflecting on azure waters, intricate jharokhas, centuries-old miniature painting traditions, and living Rajputana culture.',
      shortBio: 'Historic capital of Mewar, acclaimed as the Venice of the East with picturesque lakes, royal havelis, and vibrant arts.',
      heroImage: '/images/places/city-palace.jpg',
      heroBanner: '/images/places/city-palace.jpg',
      gallery: [
        '/images/places/city-palace.jpg',
        '/images/places/lake-pichola.jpg',
        '/images/places/jagdish-temple.jpg',
        '/images/places/bagore-ki-haveli.jpg',
        '/images/places/sajjangarh.jpg',
      ],
      coordinates: { lat: 24.5854, lng: 73.7125 },
      bestSeason: 'September – March',
      idealDurationDays: 3,
      bestDuration: '3–5 Days',
      approxBudgetPerDay: { budget: 1800, comfort: 4500, luxury: 16000 },
      weather: { tempC: 26, condition: 'Pleasant & Clear', humidity: '42%' },
      tourismStatus: {
        safetyScore: '4.9 / 5.0 (High Tourist Safety)',
        crowdLevel: 'Moderate',
        peakHours: '4:30 PM – 7:30 PM (Lakeside & Ghats)',
      },
      tags: ['Heritage', 'Lakes', 'Palaces', 'Culture', 'Romantic'],
      travelStyles: ['Heritage & Architecture', 'Cultural & Spiritual', 'Romantic & Leisure', 'Food & Culinary'],
      curatedForStyles: [
        {
          styleId: 'art',
          styleTitle: 'Mewar Art & Vintage Heritage',
          description: 'Tailored selection prioritizing 400-year-old royal craftsmanship, miniature painting ateliers, royal vintage automobiles, and palace architecture.',
          recommendedPlaceIds: ['city-palace', 'bagore-ki-haveli', 'vintage-car-museum', 'jagdish-temple', 'sajjangarh', 'lake-pichola', 'shilpgram'],
        },
        {
          styleId: 'romantic',
          styleTitle: 'Romantic Lakes & Sunsets',
          description: 'Lakeside palaces, sunset cruises, rooftop candlelight dinners and ghat views.',
          recommendedPlaceIds: ['lake-pichola', 'city-palace', 'bagore-ki-haveli', 'sajjangarh'],
        },
      ],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 96,
      dataHealth: 95,
      lastVerified: new Date(),
      verifiedBy: 'Operations Admin',
      attractionsCount: 8,
      hotelsCount: 6,
      restaurantsCount: 8,
      experiencesCount: 5,
    })

    // 4. Seed Jaipur Destination
    const jaipur = await Destination.create({
      name: 'Jaipur',
      slug: 'jaipur',
      state: 'Rajasthan',
      region: 'Dhundhar',
      country: 'India',
      locality: 'Pink City',
      tagline: 'The Pink City of Fortresses & Royal Observatories',
      description: 'Capital of Rajasthan, famed for majestic hill forts, UNESCO World Heritage astronomical observatories, and vibrant bazaars.',
      shortBio: 'The historic Pink City, established in 1727 by Maharaja Sawai Jai Singh II with grid architecture and iconic pink terracotta facades.',
      heroImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
      heroBanner: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1603288940316-4e43bf17730a?auto=format&fit=crop&w=800&q=80',
      ],
      coordinates: { lat: 26.9124, lng: 75.7873 },
      bestSeason: 'October – March',
      idealDurationDays: 3,
      bestDuration: '3–4 Days',
      approxBudgetPerDay: { budget: 1600, comfort: 4000, luxury: 14000 },
      weather: { tempC: 27, condition: 'Sunny & Crisp', humidity: '38%' },
      tourismStatus: { safetyScore: '4.8 / 5.0', crowdLevel: 'High', peakHours: '10:00 AM – 5:00 PM' },
      tags: ['UNESCO Heritage', 'Forts', 'Bazaars', 'Architecture'],
      travelStyles: ['Heritage & Architecture', 'Shopping & Textiles', 'Royal Palaces'],
      featured: true,
      status: 'published',
      verificationStatus: 'verified',
      tripEngineReadiness: 92,
      dataHealth: 90,
      lastVerified: new Date(),
      verifiedBy: 'Operations Admin',
      attractionsCount: 5,
      hotelsCount: 4,
      restaurantsCount: 5,
      experiencesCount: 3,
    })

    // 5. Seed Authentic Udaipur Attractions
    const udaipurAttractions = [
      {
        id: 'city-palace',
        name: 'City Palace Complex',
        hindiName: 'सिटी पैलेस, उदयपुर',
        slug: 'city-palace',
        category: 'palace',
        categoryLabel: 'Royal Palace Complex',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'A towering granite and marble palace complex built over nearly four centuries by 22 successive Maharanas of Mewar. Rising dramatically over the eastern banks of Lake Pichola, it features an ensemble of 11 distinct palaces, hanging courtyards, mirror mosaics, and private royal chambers.',
        shortDescription: 'Monumental 400-year-old Rajput architectural triumph overlooking Lake Pichola',
        tagline: 'Monumental 400-year-old Rajput architectural triumph overlooking Lake Pichola',
        coordinates: { lat: 24.5764, lng: 73.6835 },
        address: 'Old City, Udaipur, Rajasthan 313001',
        heroImage: '/images/places/city-palace.jpg',
        images: ['/images/places/city-palace.jpg', '/images/places/lake-pichola.jpg'],
        entryFee: { indian: 300, foreign: 300, student: 100, camera: 250, priceType: 'fixed' },
        timings: '9:00 AM – 5:30 PM (Daily)',
        recommendedVisitDurationMin: 180,
        timeRequired: '2.5 – 3 Hours',
        rating: 4.8,
        reviewCount: 38400,
        importanceScore: 10,
        culturalScore: 10,
        historicalScore: 10,
        popularityScore: 10,
        uniquenessScore: 9,
        priorityCategory: 'must_see',
        familyFriendly: true,
        accessibility: true,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Construction began in 1559 by Maharana Udai Singh II after fleeing Chittorgarh. Extended over 400 years by subsequent Mewar Maharanas.',
          architecturalStyle: 'Flamboyant Rajasthani & Mughal Fusion Architecture',
          architectureHighlights: ['Mor Chowk (Peacock Courtyard) with 5,000 glass mosaics', 'Sheesh Mahal (Palace of Mirrors)', 'Amar Vilas elevated garden courtyard'],
          legendsAndStories: ['Mewar rulers claim direct descent from Surya (The Sun God); gold sun emblems adorn the royal courts.'],
          bestPhotoSpots: ['Tripolia Gate archway framing the palace facade', 'Zenana Mahal courtyard', 'Badi Mahal terrace looking out to Lake Pichola'],
          audioGuideAvailable: true,
        },
        tags: ['Palace', 'Heritage', 'Architecture', 'Mewar', 'ASI Verified'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 1240,
        usedInCollectionsCount: 88,
      },
      {
        id: 'lake-pichola',
        name: 'Lake Pichola & Sunset Cruise',
        hindiName: 'पिछोला झील',
        slug: 'lake-pichola',
        category: 'lake',
        categoryLabel: 'Historic Freshwater Lake',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'Iconic freshwater lake created in 1362 AD by Banjara tribesman Pichhu and later expanded by Maharana Udai Singh II. Shelters the world-renowned Lake Palace (Jag Niwas) and Jag Mandir island palace.',
        shortDescription: 'Historic 14th-century artificial freshwater lake with island palaces',
        tagline: 'Tranquil waters reflecting royal island palaces against the Aravalli hills',
        coordinates: { lat: 24.575, lng: 73.678 },
        address: 'Rameshwar Ghat / City Palace Jetty, Udaipur',
        heroImage: '/images/places/lake-pichola.jpg',
        images: ['/images/places/lake-pichola.jpg', '/images/places/city-palace.jpg'],
        entryFee: { indian: 500, foreign: 800, student: 300, camera: 0, priceType: 'fixed' },
        timings: '10:00 AM – 6:30 PM (Daily)',
        recommendedVisitDurationMin: 90,
        timeRequired: '1.5 Hours',
        rating: 4.9,
        reviewCount: 29500,
        importanceScore: 10,
        culturalScore: 9,
        historicalScore: 9,
        popularityScore: 10,
        uniquenessScore: 10,
        priorityCategory: 'must_see',
        familyFriendly: true,
        accessibility: true,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Engineered in 1362 AD to transport grain across streams; fortified in 1559 AD by Maharana Udai Singh II.',
          architecturalStyle: 'Water Heritage & Royal Island Pavilions',
          architectureHighlights: ['Jag Mandir Island Palace with yellow sandstone carved elephants', 'Lake Palace marble pavilion reflections'],
          legendsAndStories: ['Prince Khurram (later Emperor Shah Jahan) sought refuge at Jag Mandir in 1623; inspired designs for the Taj Mahal.'],
          bestPhotoSpots: ['Gangaur Ghat steps during sunset', 'Boat cruise passing the marble facade of City Palace'],
          audioGuideAvailable: true,
        },
        tags: ['Lake', 'Boat Cruise', 'Sunset', 'Island Palace', 'Romantic'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 1180,
        usedInCollectionsCount: 75,
      },
      {
        id: 'jagdish-temple',
        name: 'Shree Jagdish Temple',
        hindiName: 'श्री जगदीश मंदिर',
        slug: 'jagdish-temple',
        category: 'temple',
        categoryLabel: 'Indo-Aryan Stone Temple',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'Consecrated in 1651 AD by Maharana Jagat Singh I, this three-storied carved stone temple is dedicated to Lord Vishnu as Jagannath. Features a 79-foot high spire (shikhara) adorned with sculptures of dancers, musicians, and celestial beings.',
        shortDescription: '1651 AD Indo-Aryan temple with towering carved shikhara',
        tagline: 'Living stone-carved Vishnu temple pulsating with devotional hymns',
        coordinates: { lat: 24.5795, lng: 73.6841 },
        address: 'Jagdish Chowk, Old City, Udaipur 313001',
        heroImage: '/images/places/jagdish-temple.jpg',
        images: ['/images/places/jagdish-temple.jpg'],
        entryFee: { indian: 0, foreign: 0, student: 0, camera: 0, priceType: 'free' },
        timings: '5:00 AM – 12:30 PM, 4:00 PM – 9:00 PM',
        recommendedVisitDurationMin: 60,
        timeRequired: '1 Hour',
        rating: 4.7,
        reviewCount: 14200,
        importanceScore: 8,
        culturalScore: 10,
        historicalScore: 9,
        popularityScore: 8,
        uniquenessScore: 9,
        priorityCategory: 'recommended',
        familyFriendly: true,
        accessibility: false,
        photography: false,
        isAsiVerified: true,
        journeyLens: {
          history: 'Constructed at a cost of 1.5 million rupees in 1651 AD. Survived Mughal raids due to brave Mewar defensive warriors.',
          architecturalStyle: 'Maha-Gurjara & Indo-Aryan Temple Architecture',
          architectureHighlights: ['79-foot high sandstone Shikhara', 'Brass Garuda deity statue', 'Intricately carved elephant bands and apsara reliefs'],
          legendsAndStories: ['Continuous morning Aarti bells that have rung uninterrupted since the 17th century.'],
          bestPhotoSpots: ['Steep marble staircase entrance framed by carved stone elephants'],
          audioGuideAvailable: false,
        },
        tags: ['Temple', 'Spiritual', 'Indo-Aryan', 'ASI Verified', 'Heritage'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 890,
        usedInCollectionsCount: 42,
      },
      {
        id: 'bagore-ki-haveli',
        name: 'Bagore Ki Haveli & Dharohar Folk Arts',
        hindiName: 'बागोर की हवेली',
        slug: 'bagore-ki-haveli',
        category: 'heritage',
        categoryLabel: 'Royal Haveli Museum',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'An expansive 18th-century royal haveli built on Gangaur Ghat by Prime Minister Amar Chand Badwa. Boasts over 100 rooms displaying royal Mewar costumes, antique hookahs, Rajasthani puppets, and the famous evening Dharohar folk dance.',
        shortDescription: '18th-century waterfront mansion hosting renowned Rajasthani folk dances',
        tagline: 'Waterfront royal haveli hosting Rajasthan’s premier folk dance spectacle',
        coordinates: { lat: 24.5802, lng: 73.6823 },
        address: 'Gangaur Ghat Marg, Udaipur 313001',
        heroImage: '/images/places/bagore-ki-haveli.jpg',
        images: ['/images/places/bagore-ki-haveli.jpg'],
        entryFee: { indian: 100, foreign: 200, student: 50, camera: 100, priceType: 'fixed' },
        timings: '9:30 AM – 5:30 PM (Museum), 7:00 PM – 8:00 PM (Dharohar Dance)',
        recommendedVisitDurationMin: 120,
        timeRequired: '2 Hours',
        rating: 4.8,
        reviewCount: 22000,
        importanceScore: 9,
        culturalScore: 10,
        historicalScore: 9,
        popularityScore: 9,
        uniquenessScore: 9,
        priorityCategory: 'must_see',
        familyFriendly: true,
        accessibility: true,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Built by Mewar Prime Minister Amar Chand Badwa between 1751 and 1778; restored by West Zone Cultural Centre in 1986.',
          architecturalStyle: 'Traditional Mewari Haveli Architecture',
          architectureHighlights: ['Khatkhokh mirror mosaic work', 'Waterfront Gangaur Ghat triple archway', 'Neem Chowk open-air amphitheater'],
          legendsAndStories: ['Features the world’s largest verified royal turban on exhibit inside the costume gallery.'],
          bestPhotoSpots: ['Gangaur Ghat triple-arch gate framing Lake Pichola', 'Rooftop jharokha overlooking the sunset over Pichola'],
          audioGuideAvailable: true,
        },
        tags: ['Haveli', 'Folk Dance', 'Culture', 'Museum', 'Heritage'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 950,
        usedInCollectionsCount: 60,
      },
      {
        id: 'sajjangarh',
        name: 'Sajjangarh (Monsoon Palace)',
        hindiName: 'सज्जनगढ़ पैलेस',
        slug: 'sajjangarh',
        category: 'fort',
        categoryLabel: 'Hilltop Monsoon Palace',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'Perched 3,100 feet above sea level atop the Bansdara peak of the Aravalli range. Built in 1884 by Maharana Sajjan Singh as an astronomical observatory and monsoon retreat with panoramic sunset views.',
        shortDescription: 'Perched 3,100 feet in the clouds with panoramic sunset views over Mewar',
        tagline: 'Royal clifftop observatory offering sunset vistas across the Aravalli range',
        coordinates: { lat: 24.5939, lng: 73.6397 },
        address: 'Bansdara Peak, Sajjangarh Wildlife Sanctuary, Udaipur',
        heroImage: '/images/places/sajjangarh.jpg',
        images: ['/images/places/sajjangarh.jpg'],
        entryFee: { indian: 160, foreign: 300, student: 60, camera: 100, priceType: 'fixed' },
        timings: '9:00 AM – 6:30 PM (Daily)',
        recommendedVisitDurationMin: 120,
        timeRequired: '2 Hours',
        rating: 4.6,
        reviewCount: 18500,
        importanceScore: 8,
        culturalScore: 7,
        historicalScore: 8,
        popularityScore: 9,
        uniquenessScore: 9,
        priorityCategory: 'recommended',
        familyFriendly: true,
        accessibility: false,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Envisioned by Maharana Sajjan Singh in 1884 to track cloud movements; served as a hunting lodge and monsoon resort.',
          architecturalStyle: 'White Marble Hilltop Fortress & Rajput Retreat',
          architectureHighlights: ['High turrets and crenellated battlements', 'Central domed marble hall with rainwater harvesting shaft'],
          legendsAndStories: ['Featured prominently as Kamal Khan’s palace in the James Bond movie Octopussy (1983).'],
          bestPhotoSpots: ['Sunset viewing terrace framing the sun dipping below the Aravalli horizon'],
          audioGuideAvailable: true,
        },
        tags: ['Fort', 'Monsoon Palace', 'Sunset', 'Panoramic View', 'Wildlife Sanctuary'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 840,
        usedInCollectionsCount: 52,
      },
      {
        id: 'vintage-car-museum',
        name: 'Royal Vintage & Classic Car Collection',
        hindiName: 'विंटेज कार म्यूजियम',
        slug: 'vintage-car-museum',
        category: 'museum',
        categoryLabel: 'Royal Automotive Museum',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'Housed in the former royal garage of the Maharanas of Mewar. Showcases rare four-in-hand carriages and pristine classic automobiles including custom Rolls-Royce Phantoms, Cadillacs, and an MG-TC convertible.',
        shortDescription: 'Pristine collection of custom Rolls-Royce, Cadillac, and royal automobiles',
        tagline: 'Centuries of royal bespoke automotive engineering preserved in running condition',
        coordinates: { lat: 24.5746, lng: 73.6934 },
        address: 'Gulab Bagh Road, Udaipur 313001',
        heroImage: '/images/places/vintage-car-museum.jpg',
        images: ['/images/places/vintage-car-museum.jpg'],
        entryFee: { indian: 400, foreign: 400, student: 250, camera: 0, priceType: 'fixed' },
        timings: '9:00 AM – 8:00 PM (Daily)',
        recommendedVisitDurationMin: 90,
        timeRequired: '1.5 Hours',
        rating: 4.5,
        reviewCount: 9200,
        importanceScore: 7,
        culturalScore: 7,
        historicalScore: 8,
        popularityScore: 7,
        uniquenessScore: 9,
        priorityCategory: 'recommended',
        familyFriendly: true,
        accessibility: true,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Inaugurated in 2000 to preserve the running automobile fleet owned by the royal Mewar dynasty since 1908.',
          architecturalStyle: 'Semi-circular colonial stone garages with Shell vintage petrol pump',
          architectureHighlights: ['1934 Rolls-Royce 20/25 HP', '1938 Cadillac Fleetwood', '1946 MG-TC roadster'],
          legendsAndStories: ['The 1934 Rolls-Royce carried Queen Elizabeth II during her state visit to Udaipur.'],
          bestPhotoSpots: ['Standing beside the crimson 1934 Rolls-Royce Phantom under the vintage Shell station banner'],
          audioGuideAvailable: false,
        },
        tags: ['Automotive', 'Vintage Cars', 'Royal Heritage', 'Museum'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 480,
        usedInCollectionsCount: 30,
      },
      {
        id: 'saheliyon-ki-bari',
        name: 'Saheliyon Ki Bari (Garden of Maidens)',
        hindiName: 'सहेलियों की बाड़ी',
        slug: 'saheliyon-ki-bari',
        category: 'nature',
        categoryLabel: 'Royal Fountains & Gardens',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'A historic ornamental garden laid out between 1710 and 1734 by Maharana Sangram Singh II for royal maidens. Features natural gravity-fed marble elephant fountains, lotus pools, and kiosks.',
        shortDescription: '18th-century royal pleasure garden with gravity-fed fountains and lotus pools',
        tagline: 'Tranquil marble pleasure gardens designed for royal maidens of Mewar',
        coordinates: { lat: 24.6016, lng: 73.6854 },
        address: 'Saheli Marg, Udaipur 313001',
        heroImage: '/images/places/saheliyon-ki-bari.jpg',
        images: ['/images/places/saheliyon-ki-bari.jpg'],
        entryFee: { indian: 20, foreign: 100, student: 10, camera: 50, priceType: 'fixed' },
        timings: '9:00 AM – 7:00 PM (Daily)',
        recommendedVisitDurationMin: 60,
        timeRequired: '1 Hour',
        rating: 4.5,
        reviewCount: 16000,
        importanceScore: 7,
        culturalScore: 8,
        historicalScore: 8,
        popularityScore: 8,
        uniquenessScore: 8,
        priorityCategory: 'recommended',
        familyFriendly: true,
        accessibility: true,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Designed by Maharana Sangram Singh II for a group of 48 female attendants who accompanied the royal princess as dowry.',
          architecturalStyle: 'Rajasthani Hydro-Architectural Garden Style',
          architectureHighlights: ['Elephant fountains sculpted from single marble blocks', 'Gravity-fed hydraulic water acoustics'],
          legendsAndStories: ['Engineered so water pressure creates the acoustic illusion of torrential monsoon rain even during dry summers.'],
          bestPhotoSpots: ['Central marble pavilion surrounded by arching fountain sprays'],
          audioGuideAvailable: false,
        },
        tags: ['Garden', 'Fountains', 'Heritage', 'Nature'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 650,
        usedInCollectionsCount: 38,
      },
      {
        id: 'shilpgram',
        name: 'Shilpgram Rural Arts & Crafts Village',
        hindiName: 'शिल्पग्राम',
        slug: 'shilpgram',
        category: 'craft',
        categoryLabel: 'Living Rural Crafts Village',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        description: 'A sprawling 70-acre living ethnographic museum nestled in the Aravalli foothills. Replicates authentic tribal and rural huts from Rajasthan, Gujarat, Goa, and Maharashtra with live potter, weaver, and mirror-work artisans.',
        shortDescription: '70-acre living ethnographic museum showcasing rural arts and master weavers',
        tagline: 'Living rural cultural village celebrating tribal artisans and folk traditions',
        coordinates: { lat: 24.6189, lng: 73.6542 },
        address: 'Hawala Khurd, Shilpgram Road, Udaipur',
        heroImage: '/images/places/shilpgram.jpg',
        images: ['/images/places/shilpgram.jpg'],
        entryFee: { indian: 50, foreign: 150, student: 25, camera: 50, priceType: 'fixed' },
        timings: '11:00 AM – 7:00 PM (Daily)',
        recommendedVisitDurationMin: 120,
        timeRequired: '2 Hours',
        rating: 4.6,
        reviewCount: 8800,
        importanceScore: 8,
        culturalScore: 10,
        historicalScore: 7,
        popularityScore: 8,
        uniquenessScore: 9,
        priorityCategory: 'recommended',
        familyFriendly: true,
        accessibility: true,
        photography: true,
        isAsiVerified: true,
        journeyLens: {
          history: 'Inaugurated in 1989 by Rajiv Gandhi to foster and preserve traditional rural handicraft skills.',
          architecturalStyle: 'Traditional Vernacular Mud & Thatch Architecture',
          architectureHighlights: ['Mandana clay relief wall murals', 'Live terracotta pottery wheels and camel cart rides'],
          legendsAndStories: ['Home to the annual 10-day Shilpgram Crafts Fair held in late December attracting master artisans from across India.'],
          bestPhotoSpots: ['Traditional mud hut painted with white chalk Mandana folk patterns'],
          audioGuideAvailable: false,
        },
        tags: ['Handicrafts', 'Village', 'Folk Art', 'Tribal', 'Shopping'],
        status: 'published',
        verificationStatus: 'verified',
        usedInTripsCount: 420,
        usedInCollectionsCount: 26,
      },
    ]

    await Attraction.insertMany(udaipurAttractions)
    console.log(`🏛️ Seeded ${udaipurAttractions.length} authentic heritage attractions for Udaipur.`)

    // 6. Seed Hotels & Stays
    const udaipurHotels = [
      {
        name: 'Taj Lake Palace',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        coordinates: { lat: 24.5756, lng: 73.6804 },
        address: 'Pichola, Udaipur, Rajasthan 313001',
        description: '18th-century white marble island palace hotel floating in the center of Lake Pichola.',
        heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
        images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80'],
        baseEstimatedPrice: 38000,
        pricePerNight: 38000,
        livePrice: 42000,
        isLivePricing: true,
        rating: 4.9,
        reviewsCount: 3200,
        tier: 'luxury',
        type: 'Heritage Lake Palace Resort',
        amenities: ['Private Boat Arrival', 'Jiva Spa Boat', 'Royal Butler Service', 'Lakeview Dining', 'Swimming Pool'],
        roomTypes: ['Palace Room', 'Historical Suite', 'Grand Royal Suite'],
        featured: true,
      },
      {
        name: 'Amet Haveli (Ambrai Heritage Stay)',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        coordinates: { lat: 24.5778, lng: 73.6805 },
        address: 'Outside Chandpole, Hanuman Ghat, Udaipur 313001',
        description: '350-year-old Mewari heritage haveli right on the lakefront facing the illuminated City Palace.',
        heroImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
        images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'],
        baseEstimatedPrice: 7500,
        pricePerNight: 7500,
        livePrice: 8200,
        isLivePricing: true,
        rating: 4.7,
        reviewsCount: 1840,
        tier: 'comfort',
        type: 'Heritage Haveli Hotel',
        amenities: ['Lakefront Restaurant (Ambrai)', 'Free WiFi', 'Heritage Courtyards', 'Travel Desk'],
        roomTypes: ['Standard Heritage', 'Deluxe Lake View', 'Suite'],
        featured: true,
      },
      {
        name: 'Moustache Udaipur Heritage Hostel & Stays',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        coordinates: { lat: 24.5812, lng: 73.6841 },
        address: 'Gadiya Devra, Near Jagdish Temple, Udaipur 313001',
        description: 'Boutique backpacker & budget heritage property with rooftop café overlooking Jagdish Temple.',
        heroImage: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80',
        images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80'],
        baseEstimatedPrice: 1600,
        pricePerNight: 1600,
        livePrice: 1800,
        isLivePricing: true,
        rating: 4.5,
        reviewsCount: 940,
        tier: 'budget',
        type: 'Boutique Heritage Hostel',
        amenities: ['Rooftop Café', 'High Speed WiFi', 'Shared & Private Rooms', 'Walking Tours'],
        roomTypes: ['Dormitory Bed', 'Private Double Room', 'Balcony Room'],
        featured: true,
      },
    ]

    await Hotel.insertMany(udaipurHotels)

    // 7. Seed Authentic Mewar Restaurants
    const udaipurRestaurants = [
      {
        name: 'Ambrai Restaurant',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        coordinates: { lat: 24.5778, lng: 73.6805 },
        address: 'Amet Haveli, Outside Chandpole, Udaipur 313001',
        cuisine: 'Rajasthani & North Indian Gourmet',
        priceRange: 'fine_dining',
        priceForTwo: 2200,
        rating: 4.8,
        openingHours: '12:30 PM – 3:30 PM, 7:00 PM – 11:00 PM',
        closedDays: [],
        isVeg: false,
        isVegan: false,
        isJainFriendly: true,
        localSpecialties: ['Mewari Laal Maas', 'Govind Gatte', 'Ker Sangri'],
        mustTryDishes: ['Mewari Laal Maas with Butter Naan', 'Jodhpuri Paneer Tikka'],
        description: 'Udaipur’s most celebrated open-air waterfront dining terrace directly facing City Palace, Jag Mandir, and Lake Pichola.',
        heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80'],
        featured: true,
      },
      {
        name: 'Natraj Dining Hall & Pure Veg Thali',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        coordinates: { lat: 24.5885, lng: 73.6974 },
        address: 'Near City Railway Station, Udaipur 313001',
        cuisine: 'Traditional Rajasthani & Gujarati Thali',
        priceRange: 'budget',
        priceForTwo: 600,
        rating: 4.7,
        openingHours: '11:00 AM – 3:30 PM, 6:30 PM – 10:30 PM',
        closedDays: [],
        isVeg: true,
        isVegan: false,
        isJainFriendly: true,
        localSpecialties: ['Authentic Dal Baati Churma', 'Kadhi Pakora', 'Moong Dal Halwa'],
        mustTryDishes: ['Unlimited Royal Rajasthani Thali', 'Ghee Baati with Garlic Chutney'],
        description: 'Legendary, uninterrupted 50-year-old culinary institution serving unlimited authentic ghee-roasted Dal Baati Churma.',
        heroImage: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1200&q=80',
        images: ['https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80'],
        featured: true,
      },
    ]

    await Restaurant.insertMany(udaipurRestaurants)

    // 8. Seed Cuisines & Dishes
    const rajasthaniCuisine = await Cuisine.create({
      name: 'Royal Rajasthani Cuisine',
      region: 'Mewar & Marwar',
      description: 'Centuries of desert adaptation and royal kitchen innovation utilizing stone-ground spices, pure clarified butter (ghee), and dried desert berries.',
      image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
      destinationIds: [udaipur.id, jaipur.id],
      dishCount: 4,
      signatureDishes: ['Dal Baati Churma', 'Mewari Laal Maas', 'Gatte Ki Sabzi', 'Ker Sangri'],
    })

    await Dish.create([
      {
        name: 'Traditional Dal Baati Churma',
        cuisineId: rajasthaniCuisine.id,
        cuisineName: rajasthaniCuisine.name,
        destinationId: udaipur.id,
        destinationName: 'Udaipur',
        isVeg: true,
        priceEstimate: 300,
        description: 'Crisp whole-wheat dough dumplings slow-roasted on cow-dung fire coals, dipped in hot desi ghee, served with 5-lentil panchmel dal and sweet powdered jaggery churma.',
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
        flavorProfile: 'Rich, Savory, Sweet & Ghee-infused',
      },
      {
        name: 'Mewari Laal Maas',
        cuisineId: rajasthaniCuisine.id,
        cuisineName: rajasthaniCuisine.name,
        destinationId: udaipur.id,
        destinationName: 'Udaipur',
        isVeg: false,
        priceEstimate: 650,
        description: 'Fiery royal mutton curry infused with authentic smoky Mathania red chillies and garlic paste, developed by Rajput warriors during desert campaigns.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
        flavorProfile: 'Fiery, Smoky, Spicy & Robust',
      },
    ])

    // 9. Seed Curated Experiences
    await Experience.create([
      {
        title: 'Sunset Boat Cruise & Jag Mandir Island Excursion',
        category: 'local_activities',
        categoryLabel: 'Scenic Cruise',
        location: 'Lake Pichola',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        duration: '1.5 Hours',
        durationMin: 90,
        price: 850,
        bestTime: '5:00 PM – 6:30 PM',
        season: 'All Year',
        coordinates: { lat: 24.575, lng: 73.678 },
        highlights: ['Golden hour photography', 'Jag Mandir courtyard stopover', 'City Palace waterfront panorama'],
        description: 'Exclusive boat tour departing from Rameshwar Ghat gliding past royal island palaces during sunset.',
        heroImage: '/images/places/lake-pichola.jpg',
        images: ['/images/places/lake-pichola.jpg'],
      },
      {
        title: 'Mewar Miniature Painting Masterclass at Master Atelier',
        category: 'workshops',
        categoryLabel: 'Heritage Workshop',
        location: 'Old City Arts Enclave',
        destinationId: udaipur.id,
        destinationSlug: 'udaipur',
        destinationName: 'Udaipur',
        duration: '2 Hours',
        durationMin: 120,
        price: 1500,
        bestTime: '10:30 AM',
        season: 'All Year',
        coordinates: { lat: 24.5788, lng: 73.684 },
        highlights: ['Learn single-hair brush technique', 'Natural mineral and gold-leaf pigments', 'Take home certified handmade artwork'],
        description: 'Hands-on art workshop guided by state-award-winning Mewari miniature master artists.',
        heroImage: '/images/places/bagore-ki-haveli.jpg',
        images: ['/images/places/bagore-ki-haveli.jpg'],
      },
    ])

    // 10. Seed Media Items
    await MediaItem.create([
      {
        title: 'Udaipur City Palace Grand Facade',
        url: '/images/places/city-palace.jpg',
        altText: '400-year-old granite and marble City Palace overlooking Lake Pichola',
        caption: 'Monolithic City Palace complex illuminated by morning sun.',
        source: 'Archaeological Survey of India & Mewar Tourism Archives',
        license: 'ASI Verified',
        attribution: 'Official Verified Yātra Photographic Registry',
        uploadedBy: 'Operations Admin',
      },
      {
        title: 'Lake Pichola Sunset with Island Palaces',
        url: '/images/places/lake-pichola.jpg',
        altText: 'Lake Pichola calm waters reflecting the sunset and Jag Mandir',
        caption: 'Golden hour reflection over tranquil Lake Pichola.',
        source: 'Yātra Field Documentation Team',
        license: 'Direct Ownership',
        attribution: 'Yātra Field Expedition 2026',
        uploadedBy: 'Operations Admin',
      },
    ])

    // 11. Seed Verification Request
    await VerificationRequest.create({
      entityType: 'attraction',
      entityId: 'city-palace',
      entityName: 'City Palace Complex',
      destinationName: 'Udaipur',
      submittedBy: 'Operations Admin',
      currentStatus: 'verified',
      changesSummary: 'Verified ASI accreditation, updated entry ticket tiers and winter opening hours.',
      reviewerNotes: 'All information verified with official Mewar Palace Trust ticket records.',
      verifiedBy: 'Operations Admin',
      verifiedAt: new Date(),
    })

    console.log('✨ MongoDB seeding completed successfully with 100% verified Indian heritage data!')
  } catch (err) {
    console.error('❌ Database seeding failed:', err)
  }
}
